export const editorStyles = {
  main: {
    flex: 1,
    display: 'flex',
    minHeight: 0,
    overflow: 'hidden' as const,
  },
  leftPanel: {
    width: 280,
    minWidth: 280,
    background: '#1c1c24',
    borderRight: '1px solid #27272a',
    padding: 0,
    display: 'flex',
    flexDirection: 'column' as const,
    overflowY: 'auto' as const,
    height: '100%',
  },
  panelHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '12px 16px',
    borderBottom: '1px solid #27272a',
  },
  panelHeaderTitle: {
    fontSize: 14,
    fontWeight: 600,
    color: '#e4e4e7',
  },
  section: {
    padding: '12px 16px',
    borderBottom: '1px solid #27272a',
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: 600,
    color: '#a1a1aa',
    marginBottom: 10,
    display: 'flex',
    alignItems: 'center',
    gap: 6,
  },
  canvas: {
    flex: 1,
    background: '#0c0c10',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
    minHeight: 0,
    position: 'relative' as const,
    flexDirection: 'column' as const,
  },
  input: {
    background: '#27272a',
    border: '1px solid #3f3f46',
    borderRadius: 6,
    padding: '7px 10px',
    color: '#fff',
    fontSize: 13,
    width: '100%',
    boxSizing: 'border-box' as const,
  },
  label: { display: 'block', fontSize: 12, color: '#a1a1aa', marginBottom: 4 },
  sliderRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    marginBottom: 2,
  },
  sliderLabel: {
    fontSize: 12,
    color: '#a1a1aa',
    flex: 1,
    minWidth: 0,
  },
  sliderValue: {
    fontSize: 12,
    color: '#e4e4e7',
    minWidth: 32,
    textAlign: 'right' as const,
    fontVariantNumeric: 'tabular-nums',
  },
  slider: {
    flex: 1,
    cursor: 'pointer',
    outline: 'none',
  },
  btn: (primary: boolean) => ({
    padding: '7px 16px',
    borderRadius: 6,
    border: 'none',
    background: primary ? '#6366f1' : '#27272a',
    color: '#fff',
    fontSize: 13,
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'background 0.15s',
  }),
  btnOutline: {
    padding: '7px 16px',
    borderRadius: 6,
    border: '1px solid #3f3f46',
    background: 'transparent',
    color: '#a1a1aa',
    fontSize: 12,
    cursor: 'pointer',
    width: '100%',
  },
  tabBar: {
    display: 'flex',
    gap: 2,
    background: '#27272a',
    borderRadius: 8,
    padding: 2,
  },
  tab: (active: boolean) => ({
    flex: 1,
    padding: '6px 12px',
    borderRadius: 6,
    border: 'none',
    background: active ? '#6366f1' : 'transparent',
    color: active ? '#fff' : '#71717a',
    fontSize: 12,
    fontWeight: 500,
    cursor: 'pointer',
    transition: 'all 0.15s',
  }),
};

